[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
bcrypt = "0.17.0"
rocket = "0.5.1"
rocket_db_pools = { version = "0.2.0", features = ["sqlx_sqlite"] }
rpassword = "7.4.0"
snafu = "0.8.5"
