use crate::db_manage::Note;
use maud::{html, Markup};

pub fn note_list(notes: Vec<Note>) -> Markup {
    html! {
      section style="display: flex; flex-direction: column; gap: 1rem;" {
        @for note in &notes {
          article style="
          padding: 1rem;
          border: 1px solid var(--muted-border);
          border-radius: 0.5rem;
          margin: 0rem;
        " {
            section style="margin-bottom: 0rem"{
              a { (note.name) }
            }
            p style=r#"font-size: 0.9em; color: var(--muted-color);
                       margin-bottom: 0rem"# {
              "From " (note.start_date) " to " (note.due_date)
            }

            // @if let Some(factory_id) = note.factory_id {
            //   p style="font-size: 0.75em; color: var(--muted-color); font-style: italic;" {
            //     "Generated by factory #" (factory_id)
            //   }
            // }
          }
        }

        @if notes.is_empty() {
          p style="color: var(--muted-color);" {
            "No notes to show."
          }
        }
      }
    }
}
